Hot Fix - change the `isWalletOnDevice` to not swallow any thrown Error
portal-hq/PortalSwift pull request #413
Opened 2024-09-16 23:15 UTC by AhmedRagabIssa

## Summary
- Change the `isWalletOnDevice` to not swallow any thrown Error
- Fix crash when the user passes invalid chainId to the isWalletOnDevice function line ("")

2024-09-17 14:21 UTC, blakeofwilliam approved these changes

2024-09-17 21:53 UTC, Rshahatit commented on SPM Example/PortalSwift/ViewController.swift
> +          var isWalletOnDevice = false
why is this a breaking change? hasnt the isWalletOnDevice function always specified that it throws?

2024-11-19 18:40 UTC, Rshahatit requested changes
Needs to be updated with main.

2024-11-20 17:33 UTC, Rshahatit approved these changes

2024-11-20 17:44 UTC, merged